# version: '3' # La version ya no es necesario especificarla

services:
    db:
        container_name: postgres_database
        image: postgres:15.1
        volumes:
            # - postgres-db:/var/lib/postgresql/data # ejm de referencia para utilizar volumen existente
            - ./postgres:/var/lib/postgresql/data # el ./ indica la ubicacion relativa al archivo docker-compose (sintaxis para hacer binging volumes) 
        environment:
            - POSTGRES_PASSWORD=123456
    pgAdmin:
        depends_on:
            - db
        image: dpage/pgadmin4:6.17
        ports:
            - "8090:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        environment:
            - PGADMIN_DEFAULT_PASSWORD=123456
            - PGADMIN_DEFAULT_EMAIL=superman@google.com
# volumes:
#    postgres-db:
#        external: true # Ejm de referencia para indicar el volumen a utilizar (true=volumen previamente creado)